### ISSUE TITLE
Unsolvable Puzzle

### ISSUE THREAD

**Issue by alexmmathews** [sigma144/witness-randomizer#13]
Seed: 635392
Difficulty: Expert
Version: 1.1.1
Location: Mountain; Garbage pillar floor, 4th green panel
[https://i.imgur.com/Kl42b50.png](https://i.imgur.com/Kl42b50.png)

I'm only 90% certain it is unsolvable because it is in an obscured area in the Mountain and it is slightly possible I missed something, but seems unlikely. Tried restarting, same puzzle and problem. Skipped puzzle by solving unrandomized version.

**Comment by sigma144** [comment]
Hi alexmmathews! I looked at the puzzle you mentioned and turns out there was a tetris block you were missing. It shows up better on my screen for some reason. 
<details>
  <summary>Click to see image</summary>
  
  ![puzzle](https://user-images.githubusercontent.com/3487299/89930494-d6b7a580-dbd8-11ea-83a7-c856e002cf88.png)

</details>

Those green puzzles can definitely be a bit unlucky sometimes! But one thing you can do is use the star symbols to help you find symbols that may have gotten covered up.

Also, good job getting so far in Expert mode. I'm impressed!
