### ISSUE TITLE
New Game Mode

### ISSUE THREAD

**Issue by Penguin12335** [sigma144/witness-randomizer#15]
Petition for a new game mode, **Champion mode**:
- Mix arrows with puzzles on the island, because arrow puzzles are heavily underrated 
- Rules from the Expert Mode still applies to a new mode
- the discards are similar to normal mode, as well as access into the cave

please consider this game mode, thank you
~Shadow meow

**Comment by sigma144** [comment]
Thanks for the suggestion! What I actually might end up doing eventually is adding some kind of custom option where you can choose what puzzle types you want. I chose not to use arrows much except in the cave because I thought people might have trouble figuring the mechanic out. But I like the idea of having another mode with new kinds of puzzles. I'll look into making this once my grad school course load lightens up a bit.

**Comment by sigma144** [comment]
Yeah you could choose what puzzle types you want in certain areas, and the generator would automatically come up with different ways to combine them. But what I think I will actually do in the next version is move the data that decides what puzzles to make into a separate JSON file. Then I could just send you a JSON file that adds arrows to puzzles throughout the island. I want to go with this system because it would allow creation of custom game modes without having to release a new randomizer version every time. The custom options that automatically combine mechanics will probably come later, as it's going to be a lot more complicated to make. Thanks for the feedback by the way.

**Comment by sigma144** [comment]
There are now several randomizer modes developed by the community, so I probably won't be adding any more modes to the original rando.
