### ISSUE TITLE
Puzzle solution not accepted

### ISSUE THREAD

**Issue by ChrisMusson** [sigma144/witness-randomizer#16]
I have entered a solution to a puzzle that I think is correct and it gets rejected. I inputted the puzzle in your provided solver and it gave the same solution.

![example](https://user-images.githubusercontent.com/45893675/93339495-8fe64c80-f823-11ea-805c-64081045a929.png)

It is the first elevated puzzle in the quarry/shipyard area with randomiser seed 1337. Can you confirm whether this is intended and I don't yet understand, or if this is actually a mistake.

Thank you.

**Comment by sigma144** [comment]
Hi Chris! This is actually due to a bug in the Witness' negative shape verifying algorithm. Your solution would be right if the negative 2 vertical could lie slightly off the bottom right corner of the grid, canceling two squares in the W piece. Unfortunately, any solution requiring shapes to lie partially off of the grid is not accepted by the game. I designed the generator to always make sure a solution exists that keeps all shapes on the grid, so every puzzle should still be solvable. Sadly I don't think I will be able to fix this unless I figure out a way to hack the game's shape verifying code. But thanks for taking the time to report!

Here's a general visual aid for the bug I'm talking about:
![https://github.com/sigma144/witness-randomizer/blob/master/polyex.png](https://github.com/sigma144/witness-randomizer/blob/master/polyex.png)

**Comment by sigma144** [comment]
Incase you're wondering about the intended solution, I think it's this:

<details>
  <summary>See details</summary>
  
Up, Right, Up, Left, Up, Right 2, Down 3, Right, Up 3.
  
</details>

**Comment by ChrisMusson** [comment]
Ah I see, I wasn't aware that this was a bug in the game, I have never run into it! I did find that solution - just put the 2 block on the bottom instead of the top - but thought I should report this anyway in case this behaviour wasn't known. Thank you for clearing it up.
