### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by IllianDeCube09** [sigma144/witness-randomizer#19]
I launched The Witness, started a new game, launched Witness RPG.exe, but nothing happened. For some reason the application did not start, that is, even the settings window did not open. Could I have done something wrong? As a possible reason - I do not have a licensed version of the game.

**Comment by sigma144** [comment]
What happens when you run the mod? Does any window pop up at all? One thing you might try is to right click and run the mod as administrator. It's possible your security might be blocking it. Also, what operating system are you running it on?

**Comment by IllianDeCube09** [comment]
As I understand it, this was some kind of isolated case that the program did not start, because after a while it still started. I apologize if I bothered in vain, but there may be some flaws in the source code of the program, which sometimes give an error.

I'm very glad that someone came up with a mod for an essentially not-so-popular game that gives it variety)

**Comment by sigma144** [comment]
Yay, I'm glad it worked! One thing I've noticed is that the first run always takes a while because Windows needs to do a security scan on it first. But it's very possible that there are some other corner cases that cause it to not load up sometimes. This mod is very time consuming to test, and needing it to work on different machines and game versions complicates things. But I appreciate you taking the time to report - it definitely helps me know what to look for in future testing.
