### ISSUE TITLE
Enhancement: Activate lasers automatically

### ISSUE THREAD

**Issue by sigma144** [sigma144/witness-randomizer#21]
In the next version I'd like to activate non-randomized lasers & shortcuts automatically instead of having to solve optional puzzles. However, I don't know how to trigger the activation. If anyone with hacking knowledge has some advice on this, I would be very grateful.

**Comment by jbzdarkid** [comment]
So, most things in games are triggered by other actions. So the main thing you'll have to do actually *trigger* the action. The rest is pretty easy.
Obviously, the easiest thing to do would be trigger the laser based on other in-game actions (e.g., first door in the game). The Witness uses an entity type called "Gauge" to cause one action to invoke others. For example, see how I hacked around at the end of shadows tutorial.
If you want to trigger based on some other action (one of your watchdogs, or even a button in the app), follow these steps:
1. Decide which function you're going to call. For lasers, you'd probably want `Entity_Laser::activate`, for panels you'd likely pick `Entity_Machine_Panel::finish_tracing`
2. Look up said function in the old version of the game (`download_depot 210970 210971 6699512367181293800`, then use a debugger -- VS will work)
3. Compute a sigscan, and ensure it works with the latest version of the game. This will allow you to target both versions (though you'll likely want to start by using the older one, since it'll make debugging easier).
4. Determine the function arguments and calling pattern of the target function. I'm fairly certain The Witness uses x64 fastcall for all internal functions. For `Entity_Laser::activate`, the arguments are (void), so you can infer that `Entity_Laser *this` is in `ecx`, and no other registers are needed.
5. Write your assembly. This is probably best done in the debugger, and it'll like look like this:
```
mov rax, <address of function>
mov ecx, <argument 1>
call rax
```
6. Allocate some memory using `VirtualAllocEx`, marked as `PAGE_EXECUTE_READWRITE`.
7. Write your assembly (as bytecode) into the allocated memory
8. When you decide to activate the laser, start a new thread using `CreateRemoteThread`.

**Comment by sigma144** [comment]
Wow, that's some great information, thanks darkid! I will certainly give this a try for the next version.

**Comment by NewSoupVi** [comment]
https://www.youtube.com/watch?v=jMT1VMSQTe0

https://github.com/JarnoWesthof/The-Witness-Randomizer-for-Archipelago/blob/Remote_Activate_Lasers/Source/Memory.cpp#L150

Call `_memory->ActivateLaser(0x0C2B2);`

<3

**Comment by sigma144** [comment]
Neat, thanks for the help everyone!

**Comment by NewSoupVi** [comment]
So, the thing I did actually doesn't quite work that well - It gets the thread stuck in an infinite loop, because I switched up my "sub rsp" and "add rsp"

This "works", but gets stuck in an infinite loop and wrecks your CPU after doing it a couple times:
```
mov rax [address]
mov rcx [address]
add rsp,08
call rax
sub rsp,08
ret
```

Curiously, this just crashes:
```
mov rax [address]
mov rcx [address]
sub rsp,08
call rax
add rsp,08
ret
```

However, THIS works for some reason (adding in some "safety distance", basically?):
```
mov rax [address]
mov rcx [address]
sub rsp,48
call rax
add rsp,48
ret
```

So here is the updated code: https://github.com/Jarno458/The-Witness-Randomizer-for-Archipelago/blob/master/Source/Memory.cpp#L240-L275

**Comment by sigma144** [comment]
I have pulled the code and verified that it works. This will be implemented in the next randomizer version for any lasers I am unable to randomize.
