### ISSUE TITLE
impossible puzzle

### ISSUE THREAD

**Issue by Penguin12335** [sigma144/witness-randomizer#27]
there's an impossible swamp puzzle on seed 6654 expert mode, 4th red panel at the top, i might be wrong but please check it

![error](https://user-images.githubusercontent.com/39837729/110789805-3e3aee00-82ab-11eb-9e0d-ff112e8fe884.PNG)

**Comment by medicatedshawnie** [comment]
The reason witnesspuzzles.com believes the panel to unsolvable is because witnesspuzzles does not allow for polyominoes/tetris blocks to be in the center of a panel. As such, it cannot find solutions such as the one shown here:
![SOLVED](https://user-images.githubusercontent.com/60412657/110836648-4a548a80-826e-11eb-9731-c71cc1812e76.PNG)

**Comment by sigma144** [comment]
Looks like the issue is resolved. Interesting to know that witnesspuzzles.com has that bug. The solver provided with the randomizer handles this correctly.

**Comment by medicatedshawnie** [comment]
The creator of witnesspuzzles has talked about it before. It's not a bug, just something that one has to choose whether or not to include since it never comes up in the actual base game.
