### ISSUE TITLE
unsolvable puzzle in mountain

### ISSUE THREAD

**Issue by emnesoi** [sigma144/witness-randomizer#28]
![image](https://user-images.githubusercontent.com/20587912/111022528-d367e080-8398-11eb-9e51-5389b619061d.png)
according to the solver (and way too much time spent trying to solve it on its own), there is no solution for this puzzle which allows me to access the other side of the room.

seed: 94467, normal difficulty, bridge on 2nd floor of mountain above color puzzles

**Comment by medicatedshawnie** [comment]
A valid solution is LULUULUU, though the solver that comes with the randomizer does not find this solution. (I've found other panels that that solver also cannot solve, so it has some sort of problems for sure) The solver at witnesspuzzles[https://witnesspuzzles.com/pages/editor.html](url) was able to find this solution though

**Comment by sigma144** [comment]
medicatedshawnie's solution is correct. I've noticed the solver seems to have a problem with puzzles involving multiple exits. I'll keep this in mind when my college classes are done and I try to fix the solver. I'll close this issue for now because I want to have solver bugs be tracked separately from randomizer bugs. Thanks for the report!
