### ISSUE TITLE
Unsolvable puzzles

### ISSUE THREAD

**Issue by dackid19** [sigma144/witness-randomizer#60]
In the introduction room, there is the panel that has two branching paths: one for a door and the other for the main exit. However, it appears expert mode is only testing to see if the top path is solvable. I've randomized the game 3 times and each one gives an unsolvable solution for the main exit. 
I imagine going to normal mode for a short time will help me get passed this, but I do hope this can be fixed in the near future.

**Comment by MarugawaDK** [comment]
This is intentional, it is also mentioned in the Tutorial section here: [https://github.com/sigma144/witness-randomizer/wiki/Known-Issues#tutorial-1](https://github.com/sigma144/witness-randomizer/wiki/Known-Issues#tutorial-1)

**Comment by nintenbro1** [comment]
For the most part, if you want to beat expert, you need to have faith in the randomizer's integrity

**Comment by dackid19** [comment]
I agree @nintenbro1. The mod has a built in solver that we can use to find a solution; I only used it when I felt like it wasn't solvable. Since the intro only uses dots, the solver would have no issue finding the path. However, for each iteration of that puzzle I played, the main branch was always unsolvable. The first one needed a solver to truly see that, but their were some pretty clear fail states that you had to go through in the other two seeds I attempted. As MarugawaDK mentioned, this is a known issue.

**Comment by nintenbro1** [comment]
You're right, that puzzle will always have an unsolvable solution, so let me clarify: When I said to have faith in the randomizer, I didn't mean to have faith that the puzzles will always be solvable, I meant have faith that the randomizer won't softlock you (at least not that easily). As MarugawaDK mentioned, this is listed in the Known Issues page.  However, as they also said, it is an intentional feature and not an issue.  If you click the text in the Known Issues page, it will give you a hint if you need one.
