### ISSUE TITLE
2 Problems in Town

### ISSUE THREAD

**Issue by AlanWaP** [sigma144/witness-randomizer#63]
In picture 1, solving the puzzle on the door on right hand side cannot activate the panel on the door on left hand side. I could only activate it by switching back to the normal game. (In this picture, the left one was solved so the door is now open) Is this a bug?

In picture 2, I am stuck on this puzzle. I think it is impossible to turn on the red light (i.e. make the rectangle include the square on the right) In addition, the puzzle to the left is also confusing. I tried to turn on the red light by switching to normal game, but the information then looked the same as in blue light.

In picture 3 and 4, the four puzzles on the ground here seem not working. Some look impossible to solve, others don't give response (I checked my answer several times and thought it was correct)

In picture 5, I cannot lock the gate to reach hidden path. And the bottom wire cannot be activated, because the puzzle connected to it is no possible. (See picture 6. I cannot reach the bottom end)

![1](https://user-images.githubusercontent.com/16981720/168449134-467e700a-415a-46f5-97cf-2b3b1be279e2.png) Pic 1
![2](https://user-images.githubusercontent.com/16981720/168449137-16ee1a2d-a0be-42d5-ac2f-ca4fe08a27c6.png) Pic 2
![1](https://user-images.githubusercontent.com/16981720/168493851-50afb4db-a668-4114-8b3a-d8c95ed60713.png) Pic 3
![2](https://user-images.githubusercontent.com/16981720/168494231-c31adef8-ac4f-4d78-b261-93f84abfbd2d.png) Pic 4
![3](https://user-images.githubusercontent.com/16981720/168493857-ad4d7989-1534-4e6c-b549-801770e7661a.png) Pic 5
![4](https://user-images.githubusercontent.com/16981720/168494109-1402307a-5bf3-4916-b889-3a5224a5d635.png) Pic 6

**Comment by sigma144** [comment]
Hey AlanWaP, thanks for posting!
1. The activation order in Town was changed in Expert to make it a bit harder. The 3-color room opens the door to the 3x3 puzzle outside.
2. Yes the red light is meant to be impossible here. Looks like you figured out how to solve the left side puzzle. For the right side puzzle, use what you remember from the cyan/yellow dot sym puzzles to solve it. Green & blue light alone can give you enough information to solve it.
3/4. These puzzles have a certain trick to them. In the first one you'll notice that there seems to be only 5 white stars. Could there be another symbol somewhere you can't see?
5/6. Because of the trick Expert added here, locking the gate is indeed impossible. Because of this the maximum panel count for Expert is 522. (At least until a later patch when I decide how I might want to change this.)
