### ISSUE TITLE
Randomizer Not Working Entirely

### ISSUE THREAD

**Issue by Mushycatt** [sigma144/witness-randomizer#74]
![image](https://user-images.githubusercontent.com/113127401/189174052-8fbf1fb2-25b2-463c-9044-6dcbe321682e.png)

Weird problem where opening the randomizer gives me this message but The Witness is already open! I already got the randomizer running but trying to resume my progress made me find this. Steam says my version is up to date and I installed the 1.3.1 version of the randomizer which I think is up to date too. What may be the problem?

**Comment by sigma144** [comment]
Hmm, I suppose you haven't changed the exe name since then? It only works if the process is named witness64_d3d11.exe. You could try launching the game exe straight from the game folder. If that still doesn't work, I would try running the rando in administrator mode, in case Windows is blocking it for whatever reason from accessing other processes.

**Comment by sigma144** [comment]
Closing since it's been over a week since the last update. If the fixes I mentioned do not work, please let me know.
