### ISSUE TITLE
Bug in Quarry Boathouse

### ISSUE THREAD

**Issue by Skyeward** [sigma144/witness-randomizer#76]
The final puzzle on the Quarry Walkway panels appears to be bugged. The location of the panel is shown here:

![PanelInContext](https://user-images.githubusercontent.com/6289760/194958520-7f9c328d-f408-4c74-a56c-a7a0685aee34.png)

The puzzle (and my solution) is shown in this image; the two circled symbols flashed up as an error:

![FailedSolutionPanel](https://user-images.githubusercontent.com/6289760/194958610-2465ad19-51c4-47a8-b7da-c93d1cdaeeae.png)

I checked the puzzle in the provided Solver and it showed the same solution:

![FailedSolutionSolver](https://user-images.githubusercontent.com/6289760/194958670-23ca6ba9-e40c-40d2-8515-fe9671d882d2.png)

Can provide any other helpful information :)

**Comment by MarugawaDK** [comment]
I think what you have found is a bug in the solver.
Because, I don't believe a shape is allowed to go outside the bounds, even the part of it that you remove.

**Comment by Skyeward** [comment]
Ah I think you may be right, some of the more niche aspects of the polyomino rules still trip me up.

I don't know if the solver is maintained by this repo also (I couldn't find another repo with a cursory glance) so I'll leave this open for now. If someone knows that this should be elsewhere, feel free to let me know and close the issue.

**Comment by sigma144** [comment]
Yeah the solver it's a bit buggy, it can be helpful when you are stuck but it's not fully reliable. I will close this for now since the code for that solver is a mess I wrote years ago and I don't want to deal with it right now :P (Btw the puzzle above is solvable within the rules of the actual game, you'll just need to find a solution that doesn't extend polyominoes off the grid before canceling.)
