### ISSUE TITLE
New Music Box Challenge in Expert Mode?

### ISSUE THREAD

**Issue by instr3** [sigma144/witness-randomizer#8]
Hi,

Thank you for the witness RPG mod! I really enjoyed it. It was full of surprise and an in-depth understanding of the original game. For me, the mod is like re-experiencing the original game for the first time with lots of "gotcha" moments and the joy of solving difficult puzzles.

Just a question, is the music box challenge unchanged in the expert difficulty? If not, maybe it can be improved with new mechanics and new problems, potentially allowing longer time for the challenge (I am not sure if this is feasible or not). 

Again, thanks for the great work! It is really impressive. It is such a pity that not many people know that the mod exists.

**Comment by sigma144** [comment]
Hi instr3, thanks for the feedback! I actually did try to change the challenge. However, it kept causing crashes, due to the game's puzzle generation fighting with mine. After a while of trying with no success, I decided to drop the idea, since it's already random anyway. I'm glad you liked the mod though! I'm hoping at some point that someone will make a video or something that will let more people know about it.
